engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
        - .js
        - .jsx
    checks:
      import/no-duplicates:
        enabled: false
      no-template-curly-in-string:
        enabled: false
      import/no-unresolved:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
  stylelint:
    enabled: true
  duplications:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.scss"
exclude_patterns:
  - "**/*.test.js"
  - "**/css/"
  - "**/js/"
  - "**/__tests__/"
