checks:
  identical-code:
    config:
      threshold: 100
  similar-code:
    config:
      threshold: 100
  file-lines:
    config:
      threshold: 350
  method-lines:
    config:
      threshold: 300
engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
        - .js
        - .jsx
    checks:
      import/no-duplicates:
        enabled: false
      no-template-curly-in-string:
        enabled: false
      import/no-unresolved:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
      react/jsx-curly-brace-presence:
        enabled: false
      jsx-a11y/aria-proptypes:
        enabled: false
      array-callback-return:
        enabled: false
      prefer-const:
        enabled: false
      require-jsdoc:
        enabled: false
      no-unused-expressions:
        enabled: false
      class-methods-use-this:
        enabled: false
  stylelint:
    enabled: true
  duplications:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.scss"
exclude_patterns:
  - "**/*.test.js"
  - "**/css/"
  - "**/js/"
  - "**/__tests__/"
