language: node_js
node_js:
  - "stable"
before_install:
  - "nvm install-latest-npm"
env:
  matrix:
    - REACT=16.4
sudo: false
script:
  - npm test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
